backend:
  name: github
  repo: abdelamhorizont/anima-ona # replace this with your repo info
  use_graphql: true
  # name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

local_backend: false
media_folder: static/img
public_folder: /img

collections:
  - name: "work"
    label: "Work"
    folder: "src/pages/work"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "work-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "date" }
      - { label: "Featured Image", name: "featuredimage", widget: image }
      - { label: "Cover Image", name: "cover-image", widget: image }
      - {
          label: "Content",
          name: "variable-content",
          widget: "list",
          required: false,
          types:
            [
              {
                label: "Image Section",
                name: "image-section",
                widget: "object",
                fields:
                  [
                    {
                      label: "Columns",
                      name: "columns",
                      widget: "select",
                      options: ["1", "3", "12"],
                    },
                    {
                      label: "Images",
                      name: "images",
                      widget: "list",
                      field:
                        {
                          label: "Image",
                          name: "image",
                          widget: "object",
                          fields:
                            [
                              {
                                label: "Image",
                                name: "image",
                                widget: "image",
                                required: false,
                              },
                              {
                                label: "Caption",
                                name: "caption",
                                widget: "string",
                                required: false,
                              },
                            ],
                        },
                    },
                  ],
              },
              {
                label: "Text Section",
                name: "text-section",
                widget: "object",
                field:
                  {
                    label: "Text",
                    name: "text",
                    widget: "markdown",
                    required: false,
                  },
              },
            ],
        }
      - {
          label: "Project Infos",
          name: "projectInfos",
          widget: "markdown",
          required: false,      
        } 
      - {
          label: "Tags",
          name: "tags",
          widget: "select",
          multiple: true,
          options: ["All", "Object", "Space", "Research", "Exhibition"],
        }

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - {
              label: "Video",
              name: "video",
              widget: "object",
              fields: 
              [
                { label: "Video File", name: "videoFile", widget: file, required: false },
                { label: "Fallback Image", name: "fallbackImage", widget: image, required: false }
              ]
            }
          - { label: "Landing Video", name: "landingvideo", widget: "image" }
          - { label: "Heading", name: "heading", widget: "string" }
          - { label: "Subheading", name: "subheading", widget: "string" }
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - {
              label: "Anima Ona Image",
              name: "anima-ona-image",
              widget: "object",
              fields:
                [
                  {
                    label: "Image",
                    name: "image",
                    widget: "image",
                    required: false,
                  },
                  {
                    label: "Caption",
                    name: "caption",
                    widget: "string",
                    required: false,
                  },
                ],
            }
          - { label: "Body", name: "body", widget: "markdown" }
          - {
              label: "listes Infos",
              name: "listedInfos",
              widget: "list",
              field:
                {
                  label: "Column",
                  name: "column",
                  widget: "object",
                  fields:
                  [
                    { label: "Title", name: "title", widget: "string", required: false},
                    {
                      label: "List", 
                      name: "list",
                      widget: "list",
                      field:
                        {
                          label: "List Element",
                          name: "listElement",
                          widget: "object",
                          fields: 
                           [
                            { label: "Year", name: "year", widget: "string", required: false},
                            { label: "Title", name: "title", widget: "string", required: false},
                            { label: "Location", name: "location", widget: "string", required: false},
                            { label: "Link", name: "link", widget: "object", fields: [
                              { label: "Link", name: "link", widget: "string", required: false},
                              { label: "Link Text", name: "linkText", widget: "string", required: false},
                            ]},
                          ]
                        }
                    }
                  ]
                }
                
            }
